package ephyra.app.architecture

import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import java.io.File

/**
 * TST-003 — keeps `app/src/main/baseline-prof.txt` honest.
 *
 * The profile is a hand-maintained artifact. Its own header says it is produced by running
 * `BaselineProfileGenerator` and copying the output, but nothing enforces that: the file is
 * edited by hand and nothing has ever verified that the classes it names still exist. A rule
 * naming a class that was renamed or deleted is silently ignored by the installer, so the
 * profile shrinks in effect while still looking complete in review.
 *
 * This is the same defect class the rest of this session has been about: an artifact that reads
 * as maintained and is not. The check is structural — it names the specific rule and the file it
 * expected to find — not a count, so deleting a stale rule and adding a real one cannot satisfy
 * it by editing a number.
 *
 * Scope is deliberately limited to `ephyra/` rules. Third-party rules (`androidx/`, `dagger/`,
 * `coil3/`, `android/`) are owned by their libraries and are matched against the merged dex
 * rather than this repository's sources, so asserting them here would encode a guess.
 */
class BaselineProfileRuleTest {

    private val profile: List<String> by lazy {
        val file = File(repositoryRoot(), PROFILE_PATH)
        assertTrue(file.isFile, "$PROFILE_PATH is missing; the release build would ship no baseline profile")
        file.readLines().filter { it.isNotBlank() && !it.trimStart().startsWith("#") }
    }

    @Test
    fun `every ephyra class rule resolves to a declared source file`() {
        val tracked = TrackedFiles.list(repositoryRoot())
        val missing = projectClassRules().mapNotNull { rule ->
            val declaring = declaringFileFor(rule) ?: return@mapNotNull null
            val match = tracked.any { candidate ->
                candidate.relativeTo(repositoryRoot()).invariantSeparatorsPath.endsWith("/$declaring")
            }
            if (match) null else "${rule.substringBeforeLast(';')} -> expected a tracked file ending /$declaring"
        }

        assertTrue(
            missing.isEmpty(),
            "Baseline profile names classes with no source file. The installer ignores these " +
                "rules, so the profile is quietly less effective than it reads:\n  " +
                missing.joinToString("\n  "),
        )
    }

    @Test
    fun `the profile declares at least one rule`() {
        // Without this, an emptied or fully-commented profile would satisfy the check above
        // vacuously, and `TST-003` would read as done while the release build compiles nothing
        // ahead of time.
        assertTrue(
            profile.any { it.startsWith("L") },
            "Baseline profile contains no class rules",
        )
    }

    @Test
    fun `every rule is a well-formed profile line`() {
        // `L<internal name>;` for a class, optionally `->method(sig)` and prefixed `H` for hot.
        // A typo here is silently dropped at install time, so the shape is worth asserting.
        val malformed = profile.filter { line ->
            val rule = line.removePrefix("H").removePrefix("L")
            !RULE.matches(rule)
        }
        assertTrue(
            malformed.isEmpty(),
            "Baseline profile lines that are not valid ART profile rules:\n  " +
                malformed.joinToString("\n  "),
        )
    }

    private fun projectClassRules(): List<String> =
        profile.filter { it.removePrefix("H").startsWith("L$PROJECT_PACKAGE") }

    /**
     * Maps an internal class name to the tracked source file expected to declare it.
     *
     * Kotlin's file facades are the wrinkle: `HomeScreenKt` is generated by `HomeScreen.kt`,
     * not declared by a file of its own. Nested classes are folded into the outer class, whose
     * file is what matters for the rule resolving at all.
     */
    private fun declaringFileFor(rule: String): String? {
        val internal = rule.removePrefix("H").removePrefix("L").substringBefore(';').substringBefore("->")
        if (!internal.startsWith(PROJECT_PACKAGE)) return null
        val withoutOuter = internal.substringBefore('$')
        val packagePath = withoutOuter.substringBeforeLast('/', "")
        val simpleName = withoutOuter.substringAfterLast('/')
        if (simpleName.isEmpty()) return null
        val base = if (simpleName.endsWith(FACADE_SUFFIX) && simpleName.length > FACADE_SUFFIX.length) {
            simpleName.removeSuffix(FACADE_SUFFIX)
        } else {
            simpleName
        }
        return "$packagePath/$base.kt"
    }

    private fun repositoryRoot(): File {
        var directory: File? = File(".").absoluteFile
        while (directory != null && !File(directory, "settings.gradle.kts").exists()) {
            directory = directory.parentFile
        }
        return requireNotNull(directory) { "Could not locate repository root" }
    }

    private companion object {
        const val PROFILE_PATH = "app/src/main/baseline-prof.txt"
        const val PROJECT_PACKAGE = "ephyra/"
        const val FACADE_SUFFIX = "Kt"

        /** `internal/name;` optionally followed by `->method(signature)`, after `H`/`L` are stripped. */
        val RULE = Regex("""[\w/.$]+;(->[\w/.$<>]+\([^)]*\).*)?""")
    }
}
